name: Docker Volume Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}


      - name: Build and push the Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/volume-test:latest

      - name: Run the container with the volume
        run: |
          docker volume create myvolume
          docker run --rm -v myvolume:/data ${{ secrets.DOCKER_HUB_USERNAME }}/volume-test


      - name: Verify volume contents
        run: docker run --rm -v myvolume:/data alpine cat /data/volume_test.txt


    
